/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    NEXT_PUBLIC_ELEVENLABS_AGENT_SANTA: process.env.ELEVENLABS_AGENT_SANTA,
    NEXT_PUBLIC_ELEVENLABS_AGENT_GRINCH: process.env.ELEVENLABS_AGENT_GRINCH,
    NEXT_PUBLIC_ELEVENLABS_AGENT_REINDEER: process.env.ELEVENLABS_AGENT_REINDEER,
    NEXT_PUBLIC_ELEVENLABS_AGENT_SNOWMAN: process.env.ELEVENLABS_AGENT_SNOWMAN,
    NEXT_PUBLIC_ELEVENLABS_AGENT_ELF: process.env.ELEVENLABS_AGENT_ELF,
    NEXT_PUBLIC_ELEVENLABS_AGENT_SCAMMER: process.env.ELEVENLABS_AGENT_SCAMMER,
    NEXT_PUBLIC_ELEVENLABS_AGENT_JINGBELLS: process.env.ELEVENLABS_AGENT_JINGBELLS,
    NEXT_PUBLIC_ELEVENLABS_AGENT_BARRY: process.env.ELEVENLABS_AGENT_BARRY,
    NEXT_PUBLIC_ELEVENLABS_API_KEY: process.env.ELEVENLABS_API_KEY,
  },
};

module.exports = nextConfig;
